---
language: ruby
rvm:
- 2.0.0
script:
- rake
after_success:
- rake learnery:version
- rake learnery:deploy["learnery-staging-coderdojo"]
env:
  global:
    secure: |-
      jrUUaxE+OO3mfosGPHv53uGJVRgHzEa6PUDlZ1I9EBDi06+ZrY1mt9ai0IYa
      W5mTguIXZRwaECG57kQkewEr5GGqvVQ/0cqjOkSxg7ZBysyPz1Pe5+6mCLxM
      rBdH3SpW2qUyIg3EfsqyqWNCiz2NR+Ni8PeOdBoR27h8tyuT3zw=
