---
language: ruby
rvm:
- 2.0.0
script:
- rake
after_success:
- rake learnery:deploy["learnery-staging"]
env:
  global:
    secure: |-
      gOe+vayAsMD5UdQorwBhVXC1nCskkwHJIF0I+Rm2hDme2IwwHPhA/ty3Sk3D
      jG5PXSqR6QEYe8U7INmxUFx7Leoj/fcQ8us8WNNeNndmrKBdR9+iwRkwhYbw
      dhFRqjE/1+E/klVSMyZyVa10OGUcQayVVpwjq/b+56Kxy4h95A4=
