---
language: ruby
rvm:
- 2.0.0
env:
  global:
  - secure: |-
      afqw48eSUGZRmDvuNO2WfBelbzxgAPw1QBxRrRmsJuHQDFUV9tySvQicDG1B
      aciAatIa9rGhlcDnElkNkGwQluxnUcRH2w5xCvVNhy8HzBMrd8IAD35xaGj9
      OR7GOSgsF3/vlPYuxsvVBWd7f0DIoO5HBzvPD4B7EH5puBv8YJg=
script:
- rake
- bundle exec rake learnery:deploy
